// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { GetHealthCheckData, GetHealthCheckResponses, GetTokensData, GetTokensResponses, PostAccountData, PostAccountResponses, GetLeaderboardData, GetLeaderboardResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getHealthCheck = <ThrowOnError extends boolean = false>(options?: Options<GetHealthCheckData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetHealthCheckResponses, unknown, ThrowOnError>({
        url: '/health-check',
        ...options
    });
};

export const getTokens = <ThrowOnError extends boolean = false>(options: Options<GetTokensData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetTokensResponses, unknown, ThrowOnError>({
        url: '/tokens',
        ...options
    });
};

export const postAccount = <ThrowOnError extends boolean = false>(options: Options<PostAccountData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostAccountResponses, unknown, ThrowOnError>({
        url: '/account',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getLeaderboard = <ThrowOnError extends boolean = false>(options?: Options<GetLeaderboardData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetLeaderboardResponses, unknown, ThrowOnError>({
        url: '/leaderboard',
        ...options
    });
};