// This file is auto-generated by @hey-api/openapi-ts

export type GetHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health-check';
};

export type GetHealthCheckResponses = {
    /**
     * Success
     */
    200: {
        success: boolean;
        message: string;
        responseObject?: unknown;
        statusCode: number;
    };
};

export type GetHealthCheckResponse = GetHealthCheckResponses[keyof GetHealthCheckResponses];

export type GetTokensData = {
    body?: never;
    path?: never;
    query: {
        address: string;
        chainId?: number | null;
    };
    url: '/tokens';
};

export type GetTokensResponses = {
    /**
     * Success
     */
    200: {
        success: boolean;
        message: string;
        responseObject?: Array<{
            address: string;
            balance: string;
            decimal: number;
            name: string;
            symbol: string;
            logo?: string;
        }>;
        statusCode: number;
    };
};

export type GetTokensResponse = GetTokensResponses[keyof GetTokensResponses];

export type PostAccountData = {
    body: {
        address: string;
        signature: string;
    };
    path?: never;
    query?: never;
    url: '/account';
};

export type PostAccountResponses = {
    /**
     * Success
     */
    200: {
        success: boolean;
        message: string;
        responseObject?: {
            jwt: string;
        };
        statusCode: number;
    };
};

export type PostAccountResponse = PostAccountResponses[keyof PostAccountResponses];

export type GetLeaderboardData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/leaderboard';
};

export type GetLeaderboardResponses = {
    /**
     * Success
     */
    200: {
        success: boolean;
        message: string;
        responseObject?: {
            users: Array<{
                id: number;
                address: string;
                createdAt: string;
            }>;
        };
        statusCode: number;
    };
};

export type GetLeaderboardResponse = GetLeaderboardResponses[keyof GetLeaderboardResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};